### ISSUE TITLE
Sonic > Multileg-dude

### ISSUE THREAD

**Issue by binarez** [superbiji/sanic_cegep#3]
Trop de fun avec ce jeu... je bounce à gauche et à droite. Sonic semble être avantagé par rapport à multileg-dude, must balance.

**Comment by Sirmyself** [comment]
L'équilibre va venir plus tard avec les capacités spéciales de squidnic

**Comment by superbiji** [comment]
Tu devrais participer au projet Stéphane! Ça te tenterais tu?
